### ISSUE TITLE
Eu, como conselheiro, desejo editar uma checklist já preenchida para que eu possa garantir que as informações nela sejam corretas e atualizadas.

### ISSUE THREAD

**Issue by caioaazevedo** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#139]
Critérios de Aceitação:
- [x] Ter os dados preenchidos anteriormente presentes, na nuvem, em todos os campos da página, para que o usuário altere somente os campos necessários de forma a evitar o preenchimento de campos que não precisam de atualização.

- [ ] A funcionalidade de salvar os dados da checklist, na nuvem, já atualizados deverá ser representada por um botão escrito “Atualizar”.

- [x] A ação de cancelar deverá ser representada por um botão escrito “Cancelar” que irá redirecionar para a página (router), ”/checklist”.

- [ ] Não deverá ser possível salvar uma checklist caso algum campo esteja vazio ou em branco, essa proibição deverá ser feita não só em HTML como em TypeScript, por medidas de segurança.

- [ ] Após clicar no botão “Atualizar”, uma mensagem de confirmação deverá ser apresentada, caso contrario uma mensagem de erro deverá ser apresentada no lugar.

- [ ] Todas as funções criadas deverão ser testadas com no mínimo 90% de cobertura.
