### ISSUE TITLE
TS#151 - Cadastrar uma checklist e atualizar os dados da mesma. 

### ISSUE THREAD

**Issue by pAmanda** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#151]
- [x] Atualizar as checklists para que as mesmas tenham somente  as perguntas da cliente e as perguntas da cartilha.

- [x]  Fazer referência de perguntas da checklist. Oque será enviado à nuvem não terá as perguntas mas sim uma referência às perguntas, e as respostas por completo de cada pergunta. 

- [x]  Fazer com que a checklist seja cadastrada na nuvem.

**Comment by thiagoiferreira** [comment]
Already done on previous task (TS#123)
