### ISSUE TITLE
Eu, como conselheiro, desejo preencher uma checklist de cardápio para que eu possa avaliar uma escola ao relacioná-la com a checklist.

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#50]
Critérios de aceitação:

- [x] Os campos apresentados deverão indicar os respectivos campos na _checklist_ disponível na cartilha.

- [x] Campos de "Verdadeiro" ou "Falso" deverão ser preenchidos por apenas um botão que indique uma das duas opções.

- [x] O botão de campos "V" ou "F" deverá ser de fácil visualização e entendimento, como tamanho e cores adequadas.

- [x] Para cada seção da _checklist_ deverá existir um campo de texto "Observações".

**Comment by MFire30** [comment]
This US does not have any tests for Sprint 1. Going back to Product Backlog.
