### ISSUE TITLE
Eu, como conselheiro, desejo preencher uma checklist de acompanhamento de cantinas particulares para que eu possa avaliar uma escola ao relacioná-la com a checklist.

### ISSUE THREAD

**Issue by IolaneAndrade** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#57]
Critérios de aceitação:

- [x] Os campos apresentados deverão indicar os respectivos campos na checklist disponível na cartilha.
- [x] Campos de "Verdadeiro" ou "Falso" deverão ser preenchidos por apenas um botão que indique uma das duas opções.
- [x] O botão de campos "V" ou "F" deverá ser de fácil visualização e entendimento. Ex: tamanho adequado e cores contrastantes. (pense em questões de acessibilidade)
- [x] Para cada seção da checklist deverá existir um campo de texto "Observações".
