### ISSUE TITLE
Eu, como conselheiro, desejo ter a opção de anexar imagens ao checklist de Cardápio para que elas sirvam como comprovações em meu relatório.

### ISSUE THREAD

**Issue by IolaneAndrade** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#60]
Critérios de aceitação:

- [x]  Criar campo para anexar imagens .jpg ou .png.

- [x] Aceitar imagens de resolução até 1080p (Full HD).

- [x] Deverá ser possível anexar mais de 1 imagem (OBS: nº máximo de imagens ainda devem ser definidas)

- [x] Converter para base64

- [ ] enviar para a nuvem cívica

**Comment by stebezs** [comment]
The acceptance criteria have not been met. Back to the backlog.
