### ISSUE TITLE
Eu, como conselheiro, desejo salvar o atual estado do preenchimento da checklist para que eu possa continuar preenchendo posteriormente.

### ISSUE THREAD

**Issue by stebezs** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#77]
- [x] Ter as checklists implementadas

- [x]  Não aceitar dados nulos

- [x]  Por padrão as respostas devem ser "falsas"

- [x] Enviar os dados para a nuvem cívica
