### ISSUE TITLE
Eu, como conselheiro, desejo visualizar uma checklist preenchida anteriormente para rever as avaliações nela realizadas

### ISSUE THREAD

**Issue by Thiagotrfm** [fga-gpp-mds/2017.2-AjudaConselheiro-Frontend#91]
- [ ] Uma página única mostrando os dados da checklist.
- [ ] As respostas da checklist deverão ser apresentadas como "Sim", quando ativa, e "Não", quando inativa.
- [ ] Seguir a mesma ordem da apresentação do preenchimento da checklist
- [ ] Exibir botão para editar e deletar checklist, ambos sem ações.
